name: clinicify_actions

on:
  push:
    branches: [development]
  pull_request:
    branches: [main]
env:
  NODE_ENV : ${{secrets.NODE_ENV}}
  PORT : ${{secrets.PORT}}
  MONGO_URI : ${{secrets.MONGO_URI}}
  JWT_SECRET : ${{secrets.JWT_SECRET}}
  JWT_EXPIRE : ${{secrets.JWT_EXPIRE}}

jobs:
  build:
    name: Start Server
    runs-on: ubuntu-latest
    defaults: 
      run: 
        working-directory: backend
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    
    - name: Install NPM packages
      run: npm ci
    
    - name: Build project
      run: npm start

  build2:
    name: Start Web client
    runs-on: ubuntu-latest
    defaults: 
      run: 
        working-directory: frontend
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build

