name: clinicify_actions

on:
  push:
    branches: [development]
  pull_request:
    branches: [main]
env:
  NODE_ENV : ${{NODE_ENV}}
  PORT : ${{PORT}}
  MONGO_URI : ${{MONGO_URI}}
  JWT_SECRET : ${{JWT_SECRET}}
  JWT_EXPIRE : ${{JWT_EXPIRE}}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults: 
      run: 
        working-directory: backend
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    
    - name: Install NPM packages
      run: npm ci
    

    - name: Install NPM packages
      run: npm ci
    
    - name: Build project
      run: npm start
    
    - name: Run tests
      run: npm run test

