name: clinicify_actions

on:
  push:
    branches: [development]
  pull_request:
    branches: [main]
env:
  NODE_ENV : ${{secrets.NODE_ENV}}
  PORT : ${{secrets.PORT}}
  MONGO_URI : ${{secrets.MONGO_URI}}
  JWT_SECRET : ${{secrets.JWT_SECRET}}
  JWT_EXPIRE : ${{secrets.JWT_EXPIRE}}

jobs:
  build:
    name: Start Server
    runs-on: ubuntu-latest
    defaults: 
      run: 
        working-directory: backend
    
    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    
    - run: |
        npm ci
        npm run seed
        npm start 
        cd ..
        cd frontend
        npm ci
        npm sart
        npx cypress run --record --key ${{secrets.KEY}}


    # - run: npm run build --if present
    # - run: npm install -g serve
    # - run: serve -s build

